[build]
  # React uygulamanızın build komutunu belirtin
  command = "npm run build"

  # React uygulamanızın build çıktısının bulunduğu dizin
  publish = "build"

[dev]
  # Geliştirme ortamında Netlify CLI kullanırken portu belirleyebilirsiniz.
  # Bu genellikle sadece yerel geliştirme içindir.
  command = "npm start"
  port = 3000
